### ISSUE TITLE
Where to put a System Tray item 

### ISSUE THREAD

**Issue by StasKolodyuk** [TimbrelMasters/Memo#1]
Where to put a System Tray listeners?  I think it's better to put them in view class cause tray is from awt packages. So, Vlad, it' s seems like you're responsible for writing the system tray code

**Comment by pisarik** [comment]
Okey, I developed class TrayController, which allows just set icon, menu, tip and show or hide tray. Now  task of the view is just load image, make menu and tooltip, then it must work with tray through controller:)
Yet I don't know how it would be better to make the access to this class. Maybe wrap in methods or just create method getTrayController

**Comment by StasKolodyuk** [comment]
Thanks)
